# install with:
# cargo install --force cargo-make

# run with:
# cargo make <task name>

[config]
default_to_workspace = false

[tasks.debug]
env = { "RUST_LOG" = "point_cloud=debug,wgpu=warn" }
command = "cargo"
args = [
    "run",
    "--package", "point-cloud",
    "--bin", "point_cloud"
]

[tasks.release]
env = { "RUST_LOG" = "point_cloud=debug,wgpu=warn" }
command = "cargo"
args = [
    "run",
    "--package", "point-cloud",
    "--bin", "point_cloud",
    "--release"
]

[tasks.web]
env = { "RUSTFLAGS" = "--cfg=web_sys_unstable_apis" }
command = "wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
args = [
    "build",
    "--target", "web",
    "--weak-refs",
    "--release",
    ".",
]